version: 1.0.{build}
image: Visual Studio 2013

environment:
    QT5DIR: C:\Qt\5.4

install:
    - cmd: choco install -y curl
    # Install SFML
    - cmd: curl -OJL http://www.sfml-dev.org/files/SFML-2.3-windows-vc12-32-bit.zip
    - cmd: 7z x SFML-2.3-windows-vc12-32-bit.zip
    - cmd: SET SFML_ROOT=%CD%\SFML-2.3
    # Install libpng
    - cmd: curl -OJL https://sourceforge.net/projects/libpng/files/libpng16/older-releases/1.6.12/lpng1612.7z/download
    - cmd: 7z x lpng1612.7z
    - cmd: SET PNG_INCLUDE_DIR=%CD%\lpng1612
    - cmd: SET PNG_LIBRARY_DIR=%CD%\lpng1612\projects\vstudio\Release
    # Install zlib
    - cmd: curl -OJL http://zlib.net/zlib128-dll.zip
    - cmd: 7z x zlib128-dll.zip -o%CD%\zlib128-dll
    - cmd: curl -OJL http://zlib.net/zlib128.zip
    - cmd: 7z x zlib128.zip
    - cmd: SET ZLIB_ROOT=%CD%\zlib128-dll
    # Build libpng
    - cmd: cd lpng1612\projects\vstudio
    - cmd: msbuild vstudio.sln /p:Configuration=Release
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: SET CMAKE_PREFIX_PATH=%QT5DIR%\msvc2013_opengl

build_script:
    - cmd: cmake -DCMAKE_BUILD_TYPE=Release

artifacts:
    - path: Exec
      name: Client Executable
